<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Divya-PC" name="com.qa.salesforce.test.LoginPageTest" tests="5" failures="1" timestamp="18 Aug 2022 19:58:11 GMT" time="46.393" errors="0">
  <testcase name="testCase1" time="11.741" classname="com.qa.salesforce.test.LoginPageTest"/>
  <testcase name="testCase4A" time="6.304" classname="com.qa.salesforce.test.LoginPageTest"/>
  <testcase name="testCase4B" time="6.549" classname="com.qa.salesforce.test.LoginPageTest"/>
  <testcase name="testCase2" time="10.528" classname="com.qa.salesforce.test.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Home Page ~ Salesforce - Developer Edition.] but found [Home Page ~ Salesforce - Developer Edition]">
      <![CDATA[java.lang.AssertionError: expected [Home Page ~ Salesforce - Developer Edition.] but found [Home Page ~ Salesforce - Developer Edition]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.salesforce.test.LoginPageTest.testCase2(LoginPageTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="11.271" classname="com.qa.salesforce.test.LoginPageTest"/>
</testsuite> <!-- com.qa.salesforce.test.LoginPageTest -->
